// Datos de países + estados/departamentos.
// Foco en LatAm con detalle, resto del mundo como opciones simples con estado libre.

export interface Country {
  code: string; // ISO 3166-1 alpha-2 (mayúscula)
  name: string;
  flag: string; // emoji
  dial: string; // ej. "+598"
  states?: string[]; // si está, dropdown; si no, free text
}

export const COUNTRIES: Country[] = [
  {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    dial: "+598",
    states: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavalleja",
      "Maldonado",
      "Montevideo",
      "Paysandú",
      "Río Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San José",
      "Soriano",
      "Tacuarembó",
      "Treinta y Tres",
    ],
  },
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    dial: "+54",
    states: [
      "Buenos Aires",
      "Ciudad Autónoma de Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ],
  },
  {
    code: "BR",
    name: "Brasil",
    flag: "🇧🇷",
    dial: "+55",
    states: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    dial: "+56",
    states: [
      "Arica y Parinacota",
      "Tarapacá",
      "Antofagasta",
      "Atacama",
      "Coquimbo",
      "Valparaíso",
      "Metropolitana de Santiago",
      "O'Higgins",
      "Maule",
      "Ñuble",
      "Biobío",
      "La Araucanía",
      "Los Ríos",
      "Los Lagos",
      "Aysén",
      "Magallanes",
    ],
  },
  {
    code: "PY",
    name: "Paraguay",
    flag: "🇵🇾",
    dial: "+595",
    states: [
      "Asunción",
      "Concepción",
      "San Pedro",
      "Cordillera",
      "Guairá",
      "Caaguazú",
      "Caazapá",
      "Itapúa",
      "Misiones",
      "Paraguarí",
      "Alto Paraná",
      "Central",
      "Ñeembucú",
      "Amambay",
      "Canindeyú",
      "Presidente Hayes",
      "Boquerón",
      "Alto Paraguay",
    ],
  },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", dial: "+591" },
  { code: "PE", name: "Perú", flag: "🇵🇪", dial: "+51" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", dial: "+57" },
  { code: "MX", name: "México", flag: "🇲🇽", dial: "+52" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", dial: "+593" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", dial: "+58" },
  { code: "ES", name: "España", flag: "🇪🇸", dial: "+34" },
  { code: "US", name: "Estados Unidos", flag: "🇺🇸", dial: "+1" },
  { code: "IT", name: "Italia", flag: "🇮🇹", dial: "+39" },
];

export const getCountry = (code: string | undefined | null): Country | undefined =>
  COUNTRIES.find((c) => c.code === code);

export const DEFAULT_COUNTRY_CODE = "UY";
